"""creating tables

Revision ID: bdf30b72ed12
Revises: 
Create Date: 2024-06-06 17:33:57.753965

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bdf30b72ed12'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employees',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.BIGINT(), nullable=True),
    sa.Column('fullname', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('created_at', sa.DATE(), server_default=sa.text("CAST(DATE_TRUNC('day', TIMEZONE('utc-3', now())) AS DATE)"), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('places',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('chat_id', sa.BIGINT(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chat_id')
    )
    op.create_table('finances',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('place_id', sa.INTEGER(), nullable=False),
    sa.Column('updated_at', sa.DATE(), server_default=sa.text("CAST(DATE_TRUNC('day', TIMEZONE('utc-3', now())) AS DATE)"), nullable=False),
    sa.Column('last_money', sa.Float(), nullable=False),
    sa.Column('updated_money', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['place_id'], ['places.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('place_id')
    )
    op.create_table('reports',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('report_date', sa.DATE(), server_default=sa.text("CAST(DATE_TRUNC('day', TIMEZONE('utc-3', now())) AS DATE)"), nullable=False),
    sa.Column('visitors', sa.Integer(), nullable=False),
    sa.Column('revenue', sa.Float(), nullable=False),
    sa.Column('place_id', sa.INTEGER(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['place_id'], ['places.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['employees.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reports')
    op.drop_table('finances')
    op.drop_table('places')
    op.drop_table('employees')
    # ### end Alembic commands ###
